[tool.poetry]
name = "pytest-cdist"
version = "0.1.0"
description = ""
authors = ["Kurt Schelfthout <kurt.schelfthout@gmail.com>"]
packages = [
    { include = "cdist", from = "src" },
]

[tool.poetry.plugins."pytest11"]
"cdist" = "cdist.plugin"

[tool.poetry.dependencies]
python = "^3.8"
pytest = "^7.1.2"
# meadowrun = {path = "../meadowrun"}
# meadowrun = "^0.1.13"
meadowrun = {git="https://github.com/kurtschelfthout/meadowrun.git", branch="pytest-changes"}

[tool.poetry.dev-dependencies]
black = "^22.6.0"
mypy = "^0.961"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
